// <auto-generated />
using HandmadeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HandmadeShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610150828_ImageUrl")]
    partial class ImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HandmadeShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Blanket"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Toy"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Beanie"
                        });
                });

            modelBuilder.Entity("HandmadeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price2")
                        .HasColumnType("float");

                    b.Property<double>("Price5")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "Blue",
                            Description = "Crochet Baby blanket",
                            ImageUrl = "",
                            ListPrice = 60.0,
                            Price2 = 50.0,
                            Price5 = 40.0,
                            Size = "One Size",
                            Title = "Baby Blanket"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Color = "Multicolor",
                            Description = "Theme Southpark crochet blanket",
                            ImageUrl = "",
                            ListPrice = 90.0,
                            Price2 = 80.0,
                            Price5 = 70.0,
                            Size = "One Size",
                            Title = "Southpark Blanket"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Brown",
                            Description = "Crochet Baby beanie-Bear",
                            ImageUrl = "",
                            ListPrice = 30.0,
                            Price2 = 25.0,
                            Price5 = 20.0,
                            Size = "Newborn",
                            Title = "Bear Beanie"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Color = "Gray",
                            Description = "Crochet Baby beanie-Elephant",
                            ImageUrl = "",
                            ListPrice = 40.0,
                            Price2 = 36.0,
                            Price5 = 32.0,
                            Size = "Toddler",
                            Title = "Elephant Beanie"
                        });
                });

            modelBuilder.Entity("HandmadeShop.Models.Product", b =>
                {
                    b.HasOne("HandmadeShop.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
